"""Quick quote / invoice and send (Phase 2).

The phone's flow is: pick a customer, add items, preview, submit, send. The
server builds every document with ERPNext's own logic, so prices, taxes and
totals are exactly what Desk would produce; the phone never computes money.

Everything runs as the session user. ERPNext's permissions and the price
lock (`price_lock.py`) decide what they may see and do.
"""

import re

import frappe
from frappe import _
from frappe.utils import (
	add_days,
	add_months,
	cint,
	escape_html,
	flt,
	get_formatted_email,
	get_fullname,
	nowdate,
	validate_email_address,
)

from daystar_mobile.permissions import is_mobile_sales_rep
from daystar_mobile.price_lock import validate_price_list_rates
from daystar_mobile.scope import get_company

DOCTYPES = ("Quotation", "Sales Invoice")

# Custom Field (fixture) on both doctypes, unique, so the database itself
# refuses a second document for the same draft.
IDEMPOTENCY_FIELD = "daystar_mobile_key"
_KEY_PATTERN = re.compile(r"^[A-Za-z0-9-]{16,64}$")

SEARCH_LIMIT = 20
MAX_ROWS = 100


@frappe.whitelist(methods=["GET"])
def search_customers(txt: str | None = None, limit: int = SEARCH_LIMIT):
	"""Enabled customers matching `txt`; the most recently touched first when empty."""
	txt = (txt or "").strip()
	or_filters = None
	if txt:
		like = f"%{txt}%"
		or_filters = {field: ["like", like] for field in ("name", "customer_name", "mobile_no", "email_id")}

	return frappe.get_list(
		"Customer",
		filters={"disabled": 0},
		or_filters=or_filters,
		fields=["name", "customer_name", "email_id", "mobile_no"],
		order_by="customer_name asc" if txt else "modified desc",
		limit_page_length=_limit(limit),
	)


@frappe.whitelist(methods=["GET"])
def search_items(customer: str, txt: str | None = None, limit: int = SEARCH_LIMIT):
	"""Sellable items matching `txt`, with the customer's Price List rate.

	The rate here is for the picker only. `preview` is authoritative: it runs
	ERPNext's full item pricing (pricing rules, customer-specific prices).
	"""
	frappe.has_permission("Customer", doc=customer, throw=True)
	price_list = _price_list_for(customer)

	txt = (txt or "").strip()
	or_filters = None
	if txt:
		like = f"%{txt}%"
		or_filters = {"item_code": ["like", like], "item_name": ["like", like]}

	items = frappe.get_list(
		"Item",
		filters={"disabled": 0, "is_sales_item": 1, "has_variants": 0},
		or_filters=or_filters,
		fields=["item_code", "item_name", "stock_uom", "sales_uom"],
		order_by="item_name asc",
		limit_page_length=_limit(limit),
	)

	return {
		"price_list": price_list,
		"currency": price_list and frappe.db.get_value("Price List", price_list, "currency", cache=True),
		"items": [
			{
				"item_code": item.item_code,
				"item_name": item.item_name,
				"uom": item.sales_uom or item.stock_uom,
				"rate": _list_rate(price_list, customer, item),
			}
			for item in items
		],
	}


@frappe.whitelist(methods=["GET"])
def search_documents(doctype: str, txt: str | None = None, limit: int = SEARCH_LIMIT):
	"""Submitted quotes or invoices the user can read, newest first, to send again."""
	_check_doctype(doctype)
	txt = (txt or "").strip()
	or_filters = None
	if txt:
		like = f"%{txt}%"
		or_filters = {field: ["like", like] for field in ("name", "customer_name")}

	date_field = "transaction_date" if doctype == "Quotation" else "posting_date"
	rows = frappe.get_list(
		doctype,
		filters={"company": get_company(), "docstatus": 1},
		or_filters=or_filters,
		fields=[
			"name",
			"customer_name",
			f"{date_field} as date",
			"status",
			"currency",
			"grand_total",
			"rounded_total",
		],
		order_by=f"{date_field} desc, creation desc",
		limit_page_length=_limit(limit),
	)
	return [
		{
			"doctype": doctype,
			"name": row.name,
			"customer_name": row.customer_name,
			"date": str(row.date),
			"status": row.status,
			"currency": row.currency,
			"total": row.rounded_total or row.grand_total,
		}
		for row in rows
	]


@frappe.whitelist(methods=["GET"])
def get_document(doctype: str, name: str):
	"""A submitted quote or invoice with its send defaults, as `submit` returns it."""
	_check_doctype(doctype)
	doc = frappe.get_doc(doctype, name)
	doc.check_permission("read")
	if doc.company != get_company():
		frappe.throw(_("{0} {1} isn't a Daystar document.").format(_(doctype), name), frappe.PermissionError)
	if doc.docstatus != 1:
		frappe.throw(_("Only submitted documents can be sent from the app."))
	return _submitted(doc)


@frappe.whitelist(methods=["POST"])
def preview(doctype: str, customer: str, items):
	"""The document as it would be submitted, without saving anything."""
	doc = _build(doctype, customer, items)
	return _summary(doc)


@frappe.whitelist(methods=["POST"])
def submit(doctype: str, customer: str, items, key: str):
	"""Create and submit the document once per draft.

	`key` is generated by the phone per draft and resent on every retry, so a
	retry after a dropped connection returns the document the first attempt
	created instead of making a second one.
	"""
	if not isinstance(key, str) or not _KEY_PATTERN.match(key):
		frappe.throw(_("Invalid submission key."), frappe.ValidationError)

	if existing := _find_by_key(doctype, key):
		return _submitted(existing)

	doc = _build(doctype, customer, items)
	doc.set(IDEMPOTENCY_FIELD, key)
	try:
		doc.insert()
		doc.submit()
	except frappe.UniqueValidationError:
		# A concurrent retry with the same key won the race.
		frappe.db.rollback()
		frappe.clear_messages()
		if existing := _find_by_key(doctype, key):
			return _submitted(existing)
		raise

	return _submitted(doc)


@frappe.whitelist(methods=["POST"])
def send_email(doctype: str, name: str, recipients, subject: str | None = None, message: str | None = None):
	"""Email the submitted document as a PDF, logged on its timeline.

	Sent from the user's own Email Account when they have one, otherwise from
	the site's default outgoing account.
	"""
	_check_doctype(doctype)
	doc = frappe.get_doc(doctype, name)
	doc.check_permission("email")
	if doc.docstatus != 1:
		frappe.throw(_("Submit {0} before sending it.").format(_(doctype)))

	recipients = _parse_recipients(recipients)
	account = outgoing_account_for(frappe.session.user)
	if not account:
		frappe.throw(
			_("There's no email account to send from. Ask Mlu to set one up."),
			frappe.OutgoingEmailError,
		)

	from frappe.core.doctype.communication.email import make

	result = make(
		doctype=doctype,
		name=name,
		subject=subject or default_subject(doc),
		content=message or default_message(doc),
		sender=get_formatted_email(frappe.session.user, mail=account.email_id),
		recipients=recipients,
		send_email=True,
		print_format=frappe.get_meta(doctype).default_print_format or "Standard",
		print_letterhead=True,
	)
	return {"communication": result["name"], "sender": account.email_id, "recipients": recipients}


def outgoing_account_for(user: str):
	"""The Email Account that sends for `user`: theirs, else the site default.

	Email Account is System Manager-only, so this reads it directly. It only
	picks the sender; the send itself is permission-checked on the document.
	"""
	from frappe.email.doctype.email_account.email_account import EmailAccount

	email = frappe.db.get_value("User", user, "email")
	own = frappe.db.get_value(
		"Email Account", {"enable_outgoing": 1, "email_id": email}, ["name", "email_id"], as_dict=True
	)
	if own:
		return own

	# Accounts linked on the user's record (User > Settings > Email).
	linked = frappe.get_all(
		"User Email", filters={"parent": user, "parenttype": "User"}, pluck="email_account"
	)
	if linked:
		account = frappe.db.get_value(
			"Email Account",
			{"name": ["in", linked], "enable_outgoing": 1},
			["name", "email_id"],
			as_dict=True,
		)
		if account:
			return account

	default = EmailAccount.find_default_outgoing()
	if default and default.email_id:
		return frappe._dict(name=default.name, email_id=default.email_id)
	return None


def default_subject(doc) -> str:
	return _("{0} {1} from {2}").format(_(doc.doctype), doc.name, doc.company)


def default_message(doc) -> str:
	greeting = _("Hi {0},").format(escape_html(doc.customer_name or ""))
	body = _("Please find {0} {1} attached.").format(_(doc.doctype).lower(), doc.name)
	sign_off = escape_html(get_fullname(frappe.session.user))
	return f"<p>{greeting}</p><p>{body}</p><p>{_('Kind regards,')}<br>{sign_off}<br>{doc.company}</p>"


def _build(doctype: str, customer: str, items):
	"""A new, unsaved document priced and taxed by ERPNext."""
	_check_doctype(doctype)
	frappe.has_permission(doctype, "create", throw=True)
	frappe.has_permission("Customer", doc=customer, throw=True)
	rows = _parse_rows(items)

	doc = frappe.new_doc(doctype)
	doc.company = get_company()
	today = nowdate()
	if doctype == "Quotation":
		doc.quotation_to = "Customer"
		doc.party_name = customer
		doc.transaction_date = today
		doc.valid_till = _valid_till(today)
	else:
		doc.customer = customer
		doc.posting_date = today

	# Kept by reference: pricing rules may append free-item rows.
	appended = [
		(doc.append("items", {"item_code": row["item_code"], "qty": row["qty"]}), row) for row in rows
	]

	# Customer details, price list, currency and each row's Price List rate,
	# as the form fills them in.
	doc.set_missing_values()

	# Owners may set a rate; for reps validate_price_list_rates below rejects it.
	for item, row in appended:
		if row.get("rate") is not None:
			item.rate = flt(row["rate"])

	# The company's default tax template, when the customer brought none.
	if not doc.get("taxes"):
		doc.set_taxes()
	doc.calculate_taxes_and_totals()

	# Fail at preview, not only at submit, for a rep with a changed or missing price.
	validate_price_list_rates(doc)
	return doc


def _summary(doc) -> dict:
	rounding_off = doc.is_rounded_total_disabled()
	return {
		"doctype": doc.doctype,
		"name": None if doc.is_new() else doc.name,
		"docstatus": doc.docstatus,
		"customer": doc.get("customer") or doc.get("party_name"),
		"customer_name": doc.customer_name,
		"company": doc.company,
		"currency": doc.currency,
		"price_list": doc.selling_price_list,
		"can_edit_prices": not is_mobile_sales_rep(),
		"items": [
			{
				"item_code": item.item_code,
				"item_name": item.item_name,
				"qty": item.qty,
				"uom": item.uom,
				"rate": item.rate,
				"price_list_rate": item.price_list_rate,
				"amount": item.amount,
			}
			for item in doc.items
		],
		"taxes": [
			{"description": tax.description, "rate": tax.rate, "amount": tax.tax_amount}
			for tax in doc.get("taxes")
		],
		"net_total": doc.net_total,
		"total_taxes": doc.total_taxes_and_charges,
		"grand_total": doc.grand_total,
		"rounding_adjustment": 0 if rounding_off else doc.rounding_adjustment,
		"total": doc.grand_total if rounding_off else doc.rounded_total or doc.grand_total,
	}


def _submitted(doc) -> dict:
	"""Summary plus what the send screen needs, so it opens without another call."""
	summary = _summary(doc)
	account = outgoing_account_for(frappe.session.user)
	summary["send"] = {
		"to": doc.get("contact_email") or frappe.db.get_value("Customer", summary["customer"], "email_id"),
		"from": account.email_id if account else None,
		"subject": default_subject(doc),
		"message": default_message(doc),
	}
	return summary


def _find_by_key(doctype: str, key: str):
	_check_doctype(doctype)
	names = frappe.get_list(doctype, filters={IDEMPOTENCY_FIELD: key}, pluck="name", limit_page_length=1)
	return frappe.get_doc(doctype, names[0]) if names else None


def _price_list_for(customer: str) -> str | None:
	"""The Price List a new document for `customer` would use, as ERPNext picks it."""
	from erpnext.accounts.party import get_default_price_list

	return get_default_price_list(frappe.get_cached_doc("Customer", customer)) or frappe.db.get_single_value(
		"Selling Settings", "selling_price_list"
	)


def _list_rate(price_list: str | None, customer: str, item) -> float | None:
	from erpnext.stock.get_item_details import get_conversion_factor, get_price_list_rate_for

	if not price_list:
		return None
	uom = item.sales_uom or item.stock_uom
	ctx = frappe._dict(
		price_list=price_list,
		customer=customer,
		uom=uom,
		stock_uom=item.stock_uom,
		conversion_factor=get_conversion_factor(item.item_code, uom).get("conversion_factor") or 1,
		transaction_date=nowdate(),
	)
	return get_price_list_rate_for(ctx, item.item_code) or None


def _valid_till(today: str) -> str:
	"""Same default as the Quotation form: CRM Settings days, else one month."""
	days = cint(frappe.db.get_single_value("CRM Settings", "default_valid_till"))
	return add_days(today, days) if days else add_months(today, 1)


def _parse_rows(items) -> list[dict]:
	rows = frappe.parse_json(items) if isinstance(items, str) else items
	if not isinstance(rows, list) or not rows:
		frappe.throw(_("Add at least one item."))
	if len(rows) > MAX_ROWS:
		frappe.throw(_("A document can have at most {0} items.").format(MAX_ROWS))

	parsed = []
	for idx, row in enumerate(rows, start=1):
		if not isinstance(row, dict) or not isinstance(row.get("item_code"), str):
			frappe.throw(_("Row {0}: choose an item.").format(idx))
		qty = flt(row.get("qty"))
		if qty <= 0:
			frappe.throw(_("Row {0}: quantity must be more than zero.").format(idx))
		parsed.append({"item_code": row["item_code"], "qty": qty, "rate": row.get("rate")})
	return parsed


def _parse_recipients(recipients) -> list[str]:
	if isinstance(recipients, str):
		recipients = frappe.parse_json(recipients) if recipients.strip().startswith("[") else [recipients]
	emails = [r.strip() for r in recipients or [] if isinstance(r, str) and r.strip()]
	if not emails:
		frappe.throw(_("Add an email address to send to."))
	for email in emails:
		validate_email_address(email, throw=True)
	return emails


def _check_doctype(doctype: str):
	if doctype not in DOCTYPES:
		frappe.throw(
			_("Only quotations and sales invoices can be sent from the app."), frappe.ValidationError
		)


def _limit(limit) -> int:
	return max(1, min(cint(limit) or SEARCH_LIMIT, 50))
